# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Cr', 'CR'), ('Dr', 'DR')], max_length=100)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField()),
                ('Payment_mode', models.CharField(choices=[('Wallet', 'Wallet'), ('Bank', 'Bank')], max_length=100)),
                ('Description', models.CharField(choices=[('Bill Payment', 'Bill Payment'), ('Sent to the Friend', 'Sent to the Friend'), ('Received from the Friend', 'Received from the Friend'), ('Airtime Purchase', 'Airtime Purchase'), ('Airtime Cashing', 'Airtime Cashing')], max_length=100)),
                ('Status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('addr1', models.CharField(max_length=100)),
                ('addr2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('zip1', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Review', models.CharField(max_length=100)),
                ('SignUp_Date', models.DateTimeField(auto_now_add=True)),
                ('wallet_balance', models.IntegerField(default=0)),
                ('Pro_pic', models.ImageField(upload_to='product')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.User'),
        ),
    ]
