# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='SignUp_Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
