# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pay.User')),
                ('feedback', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Excellent', 'Excellent'), ('Bad', 'Bad')], max_length=100)),
            ],
            bases=('pay.user',),
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
