# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20180927_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='user',
            name='FeedDate',
            field=models.DateTimeField(default='2018-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='Feedback',
            field=models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Excellent', 'Excellent'), ('Bad', 'Bad')], default='Good', max_length=100),
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
