# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0006_auto_20180927_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=100)),
                ('ExpirationDate', models.DateField()),
                ('CashBack', models.IntegerField()),
            ],
        ),
    ]
