# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service_type', models.CharField(choices=[('TV, Internet e Telecomunica\xe7\xf5es', 'TV, Internet e Telecomunica\xe7\xf5es'), ('Servi\xe7os P\xfablicos', 'Servi\xe7os P\xfablicos'), ('Impostos e Taxas', 'Impostos e Taxas'), ('Companhias A\xe9reas', 'Companhias A\xe9reas'), ('Empresas De Seguros', 'Empresas De Seguros'), ('Universidades e Ensino Acad\xe9mico Superior', 'Universidades e Ensino Acad\xe9mico Superior')], max_length=100)),
                ('Provider_name', models.CharField(max_length=150)),
            ],
        ),
    ]
