# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='Service_type',
            field=models.CharField(choices=[('TV, Internet e Telecomunica\xe7\xf5es', 'TV, Internet e Telecomunica\xe7\xf5es'), ('Servicos Publicos', 'Servicos Publicos'), ('Impostos e Taxas', 'Impostos e Taxas'), ('Companhias Aereas', 'Companhias Aereas'), ('Empresas De Seguros', 'Empresas De Seguros'), ('Universidades e Ensino Acad\xe9mico Superior', 'Universidades e Ensino Acad\xe9mico Superior')], max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Services'),
        ),
    ]
