# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_auto_20180928_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
