# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_complaint_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='comment_id',
        ),
        migrations.AddField(
            model_name='services',
            name='complaint',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
